pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Lint RPMs
      - check-success=Build repo
    actions:
      merge:
        method: squash
