name: Package

on: push

jobs:
  lint:
    name: Lint RPMs
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - name: Install Dependencies
        run: dnf install -y dnf-plugins-core rpmdevtools rpmlint

      - uses: actions/checkout@v5

      - name: Run .ci/lint.sh
        run: .ci/lint.sh

  build:
    name: Build repo
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - name: Install Dependencies
        run: dnf install -y dnf-plugins-core rpmdevtools rpm-sign createrepo

      - uses: actions/checkout@v5

      - name: Run .ci/build.sh
        run: .ci/build.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: repo
          path: ~/www

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Upload repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: curl https://rclone.org/install.sh | sudo bash

      - uses: actions/download-artifact@v6
        with:
          name: repo
          path: ~/www

      - uses: actions/checkout@v5

      - name: Run .ci/deploy.sh
        run: .ci/deploy.sh
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
          SFTP_PATH: ${{ secrets.SFTP_PATH }}
